### ISSUE TITLE
Association attribute value is not shown in UI in case of different tenants 

### ISSUE THREAD

**Issue by lovtsovaik** [Haulmont/jmix-multitenancy#22]
see forum topic https://forum.jmix.ru/t/ssylochnyj-atribut-ne-zagruzhaetsya-v-ui-pod-globalnym-administratorom-esli-tenanty-osnovnoj-i-dochernej-sushhnosti-raznye-ili-null/305

**Environment**
Jmix version: 1.1.3, 1.2.0-SNAPSHOT

**Test data**

- User has many-to-one association with Departments
- User and Departments have tenant fields
- one tenant t1 is created
- only one department d1 has tenant t1, departments d2 and d3 without tenants

**Steps**

- Run demo project [adduserprop.zip](https://github.com/Haulmont/jmix-multitenancy/files/8030162/adduserprop.zip)
- Login as admin/admin (global admin)
- Users > Create
- Set required fields
- Set User dep = d1
- Save
- Select created user > Edit

**AR**
"User dep" field is empty.
<img src="https://user-images.githubusercontent.com/73226373/153139523-5a9bf993-5601-4a7a-9257-cc101958cb0d.png" height="300"/> -> <img src="https://user-images.githubusercontent.com/73226373/153139577-f69a7109-c6f7-4793-b76e-bf1a8b7139f3.png" height="300"/>

It is not shown in folloiwing cases (**note that it is not standard usage**, see Haulmont/jmix-multitenancy#24):

- User and Dep without tenants
- User without tenant, and Dep with tenant
- User with tenant, and Dep without tenant
- User and Dep with different tenants

Department is shown only in case of User and Dep have the same tenants

**ER**
User dep field should be shown 

**Solution:**
Join constraint in `io.jmix.multitenancy.data.MultiTenantJoinExpressionProvider` is disabled by default. Boolean property to enable it has been added:
`jmix.multitenancy.join-same-tenant-only-enabled`

**Comment by knstvk** [comment]
The problem does not appear if fetch mode for the reference attribute is set to `UNDEFINED`.

With the default AUTO or JOIN fetch mode, the following SQL is generated in the attached project:
```
SELECT t1.ID, t1.ACTIVE, t1.EMAIL, t1.FIRST_NAME, t1.LAST_NAME, t1.PASSWORD, t1.TENANT, t1.TIME_ZONE_ID, t1.USERNAME, t1.VERSION, t1.USER_DEP_ID, t0.ID, t0.NAME, t0.TENANT, t0.VERSION 
FROM USER_ t1 
  LEFT OUTER JOIN DEPARTMENT t0 ON ((t0.ID = t1.USER_DEP_ID) AND (t0.TENANT = t1.TENANT)) 
WHERE ((t1.ID = 'b1713e0d-18e2-8bfe-b8f4-1816c67ccad7') 
  AND (('no_tenant' = 'no_tenant') OR (t1.TENANT = 'no_tenant')))
```
The problem is clearly in `t0.TENANT = t1.TENANT` condition of JOIN clause, which is generated by `MultiTenantJoinExpressionProvider`. What we can try to do:
1. Do we need this condition at all? What's its purpose? To protect from accidental connection of entities from different tenants?
2. Add `or (t0.TENANT is null and t1.TENANT is null)` (will not fix the issue for non-tenant user if tenants of entities are not null and different).
2. Add an OR condition which will evaluate to true for non-tenant user (clumsy SQL).
3. Use only `UNDEFINED` fetch mode for loading associations for non-tenant user (badly affects performance for browse screens).
4. ???

**Comment by knstvk** [comment]
Probably the same issue: Haulmont/jmix-reports#225

**Comment by lovtsovaik** [comment]
Tested on Jmix version: 1.2.0-RC1
